<?xml version="1.0" encoding="UTF-8"?><x:stylesheet xmlns:x="http://www.w3.org/1999/XSL/Transform" version="1.0"><x:template name="liConstruct"><ul class="list-group" id="speciesList"><x:for-each select="document('species.xml')/species/mod|document('verify.xml')/species/mod"><x:sort select="@name"/><x:for-each select="specie"><x:sort select="@name"/><x:call-template name="liTemplate"/></x:for-each></x:for-each></ul></x:template><x:template name="modList"><x:for-each select="document('species.xml')/species/mod|document('verify.xml')/species/mod"><x:sort select="@name"/><x:if test="@name!='' and @name!='Z-UNDEFINED'"><li class="list-group-item" data-count="{count(specie)}" value="{@name}"><x:if test="@author!='' and @author"><x:attribute name="data-toggle">popover</x:attribute><x:attribute name="data-placement">right</x:attribute><x:attribute name="data-trigger">hover</x:attribute><x:attribute name="data-boundary">viewport</x:attribute><x:attribute name="data-fallbackPlacement">["top","bottom"]</x:attribute><x:attribute name="title">Created by</x:attribute><x:attribute name="data-content"><x:value-of select="@author"/>
							Steam ID: <x:value-of select="id/@steam"/>
							Species: <x:for-each select="specie"><x:choose><x:when test="@name"><x:value-of select="@name"/></x:when><x:otherwise><x:call-template name="cap"><x:with-param name="text" select="translate(@value,'_',' ')"/><x:with-param name="capl" select="'true'"/></x:call-template></x:otherwise></x:choose><x:if test="position()!=count(../specie)">, </x:if></x:for-each></x:attribute></x:if><x:value-of select="@name"/><x:if test="count(specie)&gt;1">
						 (<x:value-of select="count(specie)"/>)
					</x:if></li></x:if></x:for-each><li class="list-group-item" value="Z-UNDEFINED">UNDEFINED</li></x:template><x:template name="liTemplate"><li data-author="{../@author}" data-mod="{../@name}" id="{@value}" value="{@value}"><x:if test="../id/@steam"><x:attribute name="data-steamid"><x:text>https://steamcommunity.com/sharedfiles/filedetails/?id=</x:text><x:value-of select="../id/@steam"/></x:attribute></x:if><x:if test="../id/@sb"><x:attribute name="data-sbid"><x:text>http://community.playstarbound.com/resources/</x:text><x:value-of select="../id/@sb"/></x:attribute></x:if><x:attribute name="class"><x:text>list-group-item </x:text><x:if test="../../@warning='true'">warning </x:if></x:attribute><button class="btn btn-dark species"><x:attribute name="class"><x:text>btn btn-</x:text><x:choose><x:when test="../../@warning='true'">warning</x:when><x:otherwise>dark</x:otherwise></x:choose><x:text> species</x:text></x:attribute><x:if test="../@name!='' and ../@name!='Z-UNDEFINED' and ../@name or ../@author!='' and ../@author"><x:attribute name="data-toggle">popover</x:attribute><x:attribute name="data-placement">right</x:attribute><x:attribute name="data-trigger">hover</x:attribute><x:attribute name="data-boundary">viewport</x:attribute><x:attribute name="data-fallbackPlacement">["top","bottom"]</x:attribute><x:attribute name="title"><x:value-of select="../@name"/></x:attribute><x:attribute name="data-content"><x:text>By </x:text><x:value-of select="../@author"/></x:attribute></x:if><span class="capitalize"><x:choose><x:when test="@name"><x:value-of select="@name"/></x:when><x:otherwise><x:value-of select="@value"/></x:otherwise></x:choose></span><x:choose><x:when test="imgOn and imgOff"><img class="off" src="img/{imgOff/@src}"/><img class="on" src="img/{imgOn/@src}"/></x:when><x:otherwise><img class="off" src="img/tab_other.png"/><img class="on" src="img/tab_other_select.png"/></x:otherwise></x:choose><span class="hover">
					{<x:value-of select="@value"/>}
				</span></button><div class="btn-group species-group"><button class="btn btn-secondary addToAll">
					Add to All
				</button><button class="btn btn-secondary removeFromAll">
					Remove from All
				</button></div></li></x:template><x:template name="tabTab"><ul class="nav nav-tabs" id="npcTab" role="tablist"><x:for-each select="document('tab.xml')/tab/*"><li class="nav-item"><a class="nav-link" data-hash="#npc{local-name()}" data-toggle="tab"><x:value-of select="local-name()"/><span class="badge badge-primary">✓</span></a></li></x:for-each></ul></x:template><x:template name="tabBody"><div class="tab-content" id="npcList"><x:for-each select="document('tab.xml')/tab/*"><div class="container tab-pane" id="npc{local-name()}"><h3><x:value-of select="title"/></h3><h5><x:value-of select="sub"/></h5><ul class="list-group"/></div></x:for-each></div></x:template><x:template name="cap"><x:param name="text"/><x:param name="capl"/><x:param name="sub" select="substring($text,1,1)"/><x:if test="string-length($text)&gt;0"><x:choose><x:when test="$sub=' '"><x:value-of select="$sub"/><x:call-template name="cap"><x:with-param name="text" select="substring($text,2)"/><x:with-param name="capl" select="'true'"/></x:call-template></x:when><x:otherwise><x:choose><x:when test="$capl='true'"><x:value-of select="translate($sub,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')"/></x:when><x:otherwise><x:value-of select="$sub"/></x:otherwise></x:choose><x:call-template name="cap"><x:with-param name="text" select="substring($text,2)"/><x:with-param name="capl" select="'false'"/></x:call-template></x:otherwise></x:choose></x:if></x:template></x:stylesheet>