"use strict";

class sc{
	constructor(value,nameOverride){
		this.value=value;
		this.name=nameOverride||value.replace(/^[a-z]/,v=>v.toUpperCase()).replace(/_[a-z]/g,v=>" "+v.slice(1).toUpperCase());;
		this.img=[`img/tab_${value}.png`,`img/tab_${value}_select.png`];
	}
}

const species=[
new sc("Attarran"),
new sc("Canids"),
new sc("Eevee"),
new sc("Indix"),
new sc("Umbreon"),
new sc("agaran"),
new sc("albinopenguin","Albino Penguin"),
new sc("alicorn"),
new sc("alpaca"),
new sc("apex"),
new sc("arachne"),
new sc("argonian"),
new sc("avali"),
new sc("avian"),
new sc("avikan"),
new sc("avonian"),
new sc("batpony"),
new sc("blattra"),
new sc("bunnykin"),
new sc("callistan"),
new sc("cat"),
new sc("catus"),
new sc("changeling"),
new sc("chicken"),
new sc("clownkin"),
new sc("cryoguin"),
new sc("demon"),
new sc("dragon"),
new sc("droden"),
new sc("eeveetwo","Eevee Two"),
new sc("elunite"),
new sc("everis"),
new sc("familiar"),
new sc("felin"),
new sc("fenerox"),
new sc("floran"),
new sc("gardevan"),
new sc("glitch"),
new sc("greckan"),
new sc("gyrusen"),
new sc("human"),
new sc("hylotl"),
new sc("inkling"),
new sc("kazdra"),
new sc("kemono"),
new sc("kineptic"),
new sc("lamia"),
new sc("lombax_pointed"),
new sc("lombax_striped"),
new sc("manicpenguin"),
new sc("mantizi"),
new sc("moogle"),
new sc("munari"),
new sc("neko"),
new sc("nightar"),
new sc("ningen"),
new sc("novakid"),
new sc("ooze"),
new sc("orcana"),
new sc("pegasus"),
new sc("peglaci"),
new sc("penguin"),
new sc("pengvolt"),
new sc("phantasm"),
new sc("phox"),
new sc("plaguin"),
new sc("ponex"),
new sc("pony"),
new sc("puffin"),
new sc("pygs"),
new sc("pyroguin"),
new sc("robopenguin"),
new sc("rockhopperpenguin","Rock Hopper Penguin"),
new sc("rodentia"),
new sc("saturn"),
new sc("scorsheep"),
new sc("sergal"),
new sc("shade"),
new sc("shadow2"),
new sc("skath"),
new sc("skelekin"),
new sc("slimeperson","Slime Person"),
new sc("su_gem"),
new sc("tauren"),
new sc("terrakin"),
new sc("tirastrolls","Tiras Trolls"),
new sc("trink"),
new sc("troll"),
new sc("unicorn"),
new sc("vampyric"),
new sc("vanillapenguin","Vanilla Penguin"),
new sc("vespoid"),
new sc("viera"),
new sc("vulpes"),
new sc("wasphive"),
new sc("webber"),
new sc("woggle"),
new sc("zombie")
]
Object.freeze(species);